server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.10.50:3310/st?characterEncoding=utf8
    username: root
    password: dockerTest
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
